server:
  port: 8080

spring:
  application:
    name: "Popcorn Palace - Movie Booking System"

  datasource:
    url: jdbc:postgresql://localhost:5432/popcorn-palace-db
    username: popcorn-palace
    password: popcorn-palace
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: public
        url: /v3/api-docs/public
    urls-primary-name: public
